index.js, lib/types/swagger_1.js, lib/types/types.js
Before changes, exceptions occurred inside node's event loop:
>Error: Unsupported format. Spec must be valid JSON or YAML.
at Object.Types.parse (/home/ivang/dev/internal-scripts/node_modules/api-spec-converter/lib/types/types.js:36:13)
at Request._callback (/home/ivang/dev/internal-scripts/node_modules/api-spec-converter/lib/types/swagger_1.js:98:21)
at Request.self.callback (/home/ivang/dev/internal-scripts/node_modules/request/request.js:368:22)
at Request.EventEmitter.emit (events.js:98:17)
at Request.<anonymous> (/home/ivang/dev/internal-scripts/node_modules/request/request.js:1219:14)
at Request.EventEmitter.emit (events.js:117:20)
at IncomingMessage.<anonymous> (/home/ivang/dev/internal-scripts/node_modules/request/request.js:1167:12)
at IncomingMessage.EventEmitter.emit …
=> Corrected error propagation

lib/types/api_blueprint.js, lib/types/base-type.js, lib/types/io_docs.js, lib/types/swagger_1.js, lib/types/swagger_2.js, lib/types/types.js, lib/types/util.js
If other converters, also reports errors as exceptions, then we need to make it generic code.
=> Catch exceptions during conversion.

index.js, lib/types/api_blueprint.js, lib/types/base-type.js, lib/types/google.js, lib/types/io_docs.js, lib/types/swagger_1.js, lib/types/swagger_2.js
Also because it already stable release we need to update version properly.
What do you think about [this](http://semver.org/spec/v2.0.0.html) standard?
Also you could simplify npm releases by using [Travis](http://docs.travis-ci.com/user/deployment/npm/)
=> Add function to get type based on format&version

lib/util.js
More OS independent way.
Plus will work if `\\` used inside path.
=> Correct path concatenation

lib/base-type.js
Some APIs have huge number of external references, for example, this one:
http://geodesystems.com/repository/swagger/api-docs
=> Limit number of parallel downloads to 5

lib/util.js
Checking for whether a path looks like an absolute URI is problematic on Windows as the drive letter specifier looks like a protocol declaration. So, we simply check for local file existence first.
=> Allow running tests on Windows

package.json, test/convert.js
* Windows doesn't have `mkdir -p` so we add a module shim
* The default 2s mocha timeout was marginal on the googleapis:Youtube test sample on my system
=> Allow running browser tests on Windows

README.md, bin/api-spec-converter, lib/base_format.js, package.json, test/convert.js, test/output/swagger_2/petstore.yaml, test/setup/browser.js, test/setup/node.js, test/test-cases.js
Added a command line option, and argument to spec.stringify, 
to allow spec output to be json or yaml formatted.
I would have called this option "format" but since this word is already heavily
used in this library to indicate the  different types of specification supported,
I used the word "syntax" to refer to the json and yaml format.
I'm open to suggestion if you have a better term!
I have added 2 test cases to validate the actual output.
The current test suites only focused on testing the conversion.
I'm new to JavaScript, so I hope the way I modified the code is reasonable!
=> Yaml output

README.md, karma.conf.js, lib/formats.js, lib/formats/openapi_3.js, lib/formats/swagger_2.js, package.json, test/input/swagger_2/petstore.json, test/output/openapi_3/petstore.json, test/test-cases.js
Refs #112 
First pass for comments. Conversion from swagger_2 to openapi_3 format. Automatic conversions of other formats through swagger_2 has not been implemented (i,e. it is currently a manual two-stage process).
Doesn't support the recently added `--order` option.
=> Add converter from swagger_2 to openapi_3

README.md
=> Fix README.md link to online converter

lib/formats/swagger_2.js
These minor changes are necessary for the APIs.guru openapi-directory update scripts to function correctly.
They allow passing `jsonRefs` arguments down through Sway (in my use-case to parse Yaml in JSON compatible mode so duplicate properties do not throw exceptions) and the passing back of an additional copy of the validated definition with remote references resolved (as relative references would break for users downloading the definitions from APIs.guru).
Tests pass.
=> Support Sway jsonRefs and definition.remotesResolved

lib/base_format.js, lib/formats/api_blueprint.js, lib/formats/google.js, lib/formats/io_docs.js, lib/formats/raml.js, lib/formats/swagger_1.js, lib/formats/wadl.js, package.json, test/output/openapi_3/OpenStack_example.json, test/output/openapi_3/XKCD.json, test/output/openapi_3/egnyte.json, test/output/openapi_3/facebook.json, test/output/openapi_3/foursquare.json, test/output/openapi_3/klout.json, test/output/openapi_3/parameters.json, test/output/openapi_3/petstore.json, test/output/openapi_3/petstore2.json, test/output/openapi_3/polls.json, test/output/openapi_3/regex_paths.json, test/output/openapi_3/sample_wadl.json, test/output/openapi_3/simplest.json, test/output/openapi_3/usatoday.json, test/output/openapi_3/youtube.json, test/output/swagger_2/parameters.json, test/output/swagger_2/polls.json, test/test-cases.js
@MikeRalphson FYI - pretty simple change, but lmk if you have concerns/suggestions. Otherwise I'll merge tomorrow.
Once this is in, I'll update the web demo (https://github.com/LucyBot-Inc/api-spec-converter/pull/138)
=> add transitive conversion to Open API 3.0 via Swagger 2.0

lib/converters/openapi3_to_swagger2.js
Missing trailing `/` character.
=> openapi3_to_swagger2; fix fixRef function

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/petstore.json, test/output/openapi_3/petstore_from_oas3.json, test/output/swagger_2/petstore_from_oas3.json
- Update tests to handle vendor json mime types 
- Test json mime types with a regex to allow vendor types
=> Add vendor specific JSON types support for OAPI3 -> Swagger2 conversion

package.json
Getting errors w/yarn when using this package because we're on a later version of Node. This package seems to work fine with 8.9.4 -- is there a reason this was pegged at Node v6?
=> Update engine to be permissive

lib/converters/openapi3_to_swagger2.js
Fixed a number of issues that were preventing my doc from being validated:
- Handle HTTP Bearer authentication
- Rename parameter `example` to `x-example`
- Remove `allowReserved` param property
Tests pass.
=> Fix up OpenAPI 3.0 -> Swagger 2.0 conversion

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/petstore.json, test/output/swagger_2/petstore_from_oas3.json
Process responses and:
- resolve headers references as they are not supported in swagger2
- convert headers from openapi3 to swagger2
=> Fixes: #158. Convert response headers from openapi3 to swagger2.

lib/formats/wadl.js, test/output/swagger_2/OpenStack_example.json, test/output/swagger_2/facebook.json, test/output/swagger_2/regex_paths.json, test/output/swagger_2/sample_wadl.json
Back in April in https://github.com/APIs-guru/openapi-directory/issues/393 I noted that the WADL converter did not de-duplicate parameters and didn't include an `info` object. This PR aims to fix this. I wasn't totally sure about the best way to populate `info.title` and `info.version` but I went with what the test harness seemed to be doing.
=> WADL reader fixes, duplicate params and missing info object

lib/converters/openapi3_to_swagger2.js
- Remove `additionalProperties` on schemas if it's a boolean, as those aren't supported
- Stop copying schema properties onto base response objects (I don't think that makes sense - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject)
- Remove `oneOf` types - those aren't supported in Swagger 2.0, so this will effectively make those types `any` (not great but I don't see a better solution if the language doesn't support it)
=> A few fixes for OAS3 to Swagger2

package-lock.json, package.json
`swagger-converter` has been updated. The new version has support for converting custom `x-` properties in operations, whereas before this patch such properties would be skipped. With this PR custom properties will now show up in the Swagger 2.x specification as well when converting `swagger_1` using api-spec-converter.
=> swagger-converter: 1.4.4 -> 1.5.1

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/petstore.json, test/output/openapi_3/petstore_from_oas3.json, test/output/swagger_2/petstore_from_oas3.json
Currently api-spec-converter creates an invalid Swagger 2 spec for operations with a non-JSON, non-form-data body type.  For example, an OAS v3 spec using the example `requestBody` from the [Considerations for File Uploads section of OAS3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#considerations-for-file-uploads):
```yaml
requestBody:
content:
application/octet-stream:
schema:
type: string
format: binary
```
is converted to:
```yaml
consumes:
- application/octet-stream
parameters:
- in: formData
name: body
type: file
responses:
'204':
description: Success
operationId: uploadFile
```
which is invalid because "if type is `file`, the consumes MUST be either `multipart/form-data`, `application/x-www-form-urlencoded` or both" according to …
=> Improve body parameter for openapi_3 to swagger_2 conversion

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/petstore.json, test/output/swagger_2/petstore_from_oas3.json
In OpenAPI v3, the `discriminator` property is a [Discriminator Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminatorObject) while in Swagger 2 it is [a string value](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object).  This pull request adds a conversion from `.discriminator.propertyName` to `.discriminator` and from `discriminator.mapping` to `.x-discriminator-value` ([for Swagger Codegen + OpenAPI Generator](https://github.com/swagger-api/swagger-codegen/pull/4252)) and `.x-ms-discriminator-value` ([for AutoRest](https://github.com/Azure/autorest/pull/474)) on the discriminated schema objects.
Kevin
=> Improve discriminator conversion for openapi_3 to swagger_2

lib/converters/openapi3_to_swagger2.js, test/output/swagger_2/petstore_from_oas3.json
In OAS v3, the content property of the [Response Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#responseObject) maps any number of media ranges to [Media Type Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#mediaTypeObject).  The current implementation would only copy `application/json` (with fallback to the first media range).  This would lose information about operations which can return multiple types and produce an invalid specification for content starting with a media range (since ranges are not allowed in Swagger 2).
This pull request includes all types from `content` in `produces` and `examples`, mapping ranges to `application/octet-stream` as a generic catch-all type.  Since Swagger 2 only supports a single …
=> openapi_3 to 2: Convert multiple response types

bin/api-spec-converter, index.js, lib/base_format.js, lib/formats/swagger_1.js
Currently `buildTagsFromPaths` is hard-coded to be `true`.
The paths are not a good way to distinguish the operations from each-other. It is better to let the developer decide on the tags that need to be used.
In addition, the paths contain characters that are incompatible (like `/`) that are converted to `__`. This does not look very good.
Removing these tags after the fact can be frustrating, because there can be overlap between intended tags and the ones generated by api-spec-converter.
Related https://github.com/LucyBot-Inc/api-spec-converter/issues/174
=> Disable buildTagsFromPaths for Swagger 1

lib/util.js
This fix means `null` values get preserved in conversions, e.g. in OpenAPI `examples` and specification extensions.
If this causes problems it will probably be better to re-add within the relevant format adaptor(s).
=> fix: preserve nulls in conversions, fixes #210

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/petstore.json, test/output/swagger_2/petstore_from_oas3.json
The OpenAPI 3 Specification defines the mapping property of the Discriminator object as ["An object to hold mappings between payload values and schema names or references."][1]  When the mapping contained a schema name, the previous code (that I wrote, whoops) would crash with
Error: Remote $ref URLs are not currently supported for openapi_3
Update the code to correctly handle schema names and to handle resolution errors more gracefully.  Update tests to cover this.
Kevin
Ref: #206
[1]: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminator-object
=> Fix openapi_3 discriminator schema name mapping to swagger_2

lib/converters/openapi3_to_swagger2.js
The OpenAPI 3 [server object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#server-object) url may be relative, i.e. without scheme and host. The Swagger 2 [Swagger object](https://swagger.io/specification/v2/#swagger-object) host and schemes fields are optional.
This PR allows scheme and host to be optional.
=> Allow optional URL host and schemes fields.

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/deprecated.yml, test/output/swagger_2/deprecated.yml, test/test-cases.js
Although both OpenAPI 3 and 2 support the `deprecated` property on Operation objects, only OpenAPI 3 supports `deprecated` on Schema objects. Convert to `x-deprecated` for OpenAPI 2, which is supported by Autorest (and possibly others).  Don't overwrite any existing `x-deprecated` property, which may contain additional deprecation information.
Kevin
=> openapi_3 to 2: Convert deprecated to x-deprecated

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/form_param.yml, test/output/swagger_2/form_param.yml
When converting an OpenAPI 3 document to OpenAPI 2, if the schema for a `formData` parameter is a reference, the name and in properties were added to the `$ref` object then lost when it was resolved.
This commit adds a test case to cover this (using an enum) and avoids the issue by resolving (and cloning) the schema before assigning name and in.
Kevin
=> openapi_3 to 2: $ref parameter missing name+in

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/form_param.yml, test/output/swagger_2/form_param.yml
The parameter in OpenAPI/Swagger 2 has the properties of schema, excluding properties which define objects, and acts like schema.  When translating, copy schema extension properties which are applicable to parameters.  Since I'm not aware of any which are incompatible, copy them all for now.
Add `x-ms-enum` to test.  Note that [Autorest](https://github.com/Azure/autorest) uses the same generated enum type for multiple parameters (and schemas) with the same `x-ms-enum.name` and values, so duplication is not an issue.
Note: This PR should apply after #231.  Only the last commit is specific to this PR.
Kevin
=> openapi_3 to 2: Copy x- props from schema to param

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/form_param.yml
The readOnly property in OAS3 declares that a schema property
> MAY be sent as part of a response but SHOULD NOT be sent as part of the request
When converting properties to `formData` parameters, skip `readOnly` properties, since they should not be sent as parameters.
Add a test to cover this.
Note: This PR should apply after #230.  Only the last commit is specific to this PR.
Kevin
=> openapi_3 to 2: Skip readOnly formData params

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/form_param.yml, test/output/swagger_2/form_param.yml
When converting schema properties to parameters in formData, if the property is required, make the parameter required, since these have the same meaning.
Kevin
=> openapi_3 to 2: Set required for formData params

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/external_ref_fragment.json, test/input/openapi_3/has_external_ref.json, test/output/swagger_2/has_external_ref.json
JSON References may reference properties with external documents as part of the URI fragment as per https://swagger.io/docs/specification/using-ref/ and https://swagger.io/specification/v2/#relative-files-with-embedded-schema-example
=> Allow external document references

package-lock.json, package.json, test/convert.js
This PR addresses the regression to #182 noted here: https://github.com/LucyBot-Inc/api-spec-converter/pull/218#discussion_r323446374
I tried to add a regression test, and the Mocha tests are succeeding, but when run in Karma they're failing for some reason.
PTAL @rbren
=> Fix unpinned version of swagger2openapi; add regression test; build dist

lib/converters/openapi3_to_swagger2.js, test/input/openapi_3/servers.yml, test/output/swagger_2/servers.json, test/test-cases.js
This PR implements support for OpenAPI 3 server variables for templated server URLs and using default values to populate the URL.
Currently, conversion to 2.0 fails for server objects using templated URLs and variables.
=> add support for openapi_3 server variables

README.md, lib/converters/openapi3_to_swagger2.js, package-lock.json, package.json, test/input/openapi_3/multiple_ref.yml, test/output/swagger_2/multiple_ref.json, test/output/swagger_2/param_schema_ref.json, test/output/swagger_2/petstore_from_oas3.json, test/output/swagger_2/request_response_ref.yml, test/test-cases.js
Please check the commit messages for the details of the changes.
In general, I believe that there is an issue with the way the code is written right now.
Many methods work and change the object that is provided to them as a parameter. As a result, many side effects happen, and this is also the reason for this issue.
My suggestion going forward is to rewrite the sections to clone the OAS3 file, change only the clone, but always reference the original OAS3 file for whatever info is required. Or alternatively, build the OAS2 file step by step by processing the OAS3 file, without cloning it. Instead of working on the cloned object and adjusting it to be OAS2. This will make the converter more robust for future changes and ease on code and generation results readability.
=> Resolve issue #248

lib/base_format.js, test/output/swagger_2/param_schema_unordered_ref.json, test/test-cases.js
In my company, there is a complaining from the developers that their parameters was being ordered in the conversion, so i think this option should be nice.
=> Adding option to prevent sorting
