LucyBot-Inc/api-spec-converter

.travis.yml

It will automatically run "npm test" on each commit or PR.
Also you need to register your project https://travis-ci.org/

Added TravisCI integration

---

lib/types/swagger_1.js
lib/types/types.js

It fix for #6 PR
I will create test cases negative test cases, to catch such errors in future.

Fix variable names.

---

bin/api-spec-converter
package.json

I use it for debug purposes, but can why other people would want such functionality.
It made as simple as possible, stdout used as output.
Argument validation is far from ideal.
I found couple bug in 'commander' library, and submitted PR  tj/commander.js#405

Initial version of CLI tool.

---

package.json
test/golden/youtube.json

Can you publish new version of npm package?
Changes with previous one is pretty big.

Update Google coverter

---

README.md

@bobby-brennan Maybe you have better ideas what to put on Twitter instead of `Wow:`

Docs: added new badges

---

lib/types/wadl.js
test/output/swagger_2/facebook.json

WADL fixes

---

lib/types/swagger_1.js

@bobby-brennan https://github.com/apigee-127/swagger-converter#options

swagger_1: setup 'buildTagsFromPaths' convertion flag

---

index.js

Allow to override how URLs and files are read.

Expose 'ResourceReaders'.

---

package.json

@bobby-brennan Can you please review it?

swagger_2: update 'sway' lib

---

README.md

Remove openapi_3 to swagger_2 conv. from README

---

lib/converters/openapi3_to_swagger2.js
test/input/openapi_3/petstore.json
test/output/swagger_2/petstore_from_oas3.json

Remove securityDefinitions.scheme after conversion.

160 remove scheme from securityDefinitions after converting to  swagger_2

---

lib/base_format.js
package-lock.json

so --order openapi works with --to openapi_3
rebuilt dist since `npm run test` does that
Note: This PR replaces closed PR #173

fixes #172: add 'components', 'servers', and 'openapi' 

---

lib/converters/openapi3_to_swagger2.js
test/input/openapi_3/common_params.json
test/output/swagger_2/common_params.json
test/test-cases.js

Adds support for common parameters at the path-level as per #191.

Support common parameters

---

index.js
lib/formats.js
package-lock.json
package.json

which allows to don't load stuff you don't need as well as let
user ignore dependencies that might be problematic
ref #208

make format dependencies optional

---

package-lock.json
package.json

Move drafter.js to optional dependencies

---

lib/converters/openapi3_to_swagger2.js

Improve code for api requests that have no content inside requestBody.

Update openApi3 to Swagger2 conversion

---

lib/converters/openapi3_to_swagger2.js

Process writeOnly properties.

---

lib/converters/openapi3_to_swagger2.js

Before the fix all the requestBody $ref was not resolved

fix requestBody $ref extraction from openapi3 to swagger2

---

lib/converters/openapi3_to_swagger2.js
test/input/openapi_3/common_params.json

Fix convert error when parameter without desctiption and schema

fix  issue #251 can not convert parameter without desctiption and schema

---

README.md
lib/converters/openapi3_to_swagger2.js
package-lock.json
package.json
test/input/openapi_3/multiple_ref.yml
test/output/swagger_2/multiple_ref.json
test/output/swagger_2/param_schema_ref.json
test/output/swagger_2/petstore_from_oas3.json
test/output/swagger_2/request_response_ref.yml
test/test-cases.js

Reverts LucyBot-Inc/api-spec-converter#267

Revert "Revert "Resolve issue #248""
